import tkinter as tk
from tkinter import Menu
from tkinter import messagebox
import datetime
import random
import os

class App:
    def __init__(self, master):
        self.master = master
        master.title("Menu Example")
        self.random_green_hue = None

        # Text area
        self.text_area = tk.Text(master, height=10, width=50)
        self.text_area.pack()

        # Menu bar
        menubar = Menu(master)
        filemenu = Menu(menubar, tearoff=0)
        filemenu.add_command(label="Get Date/Time", command=self.get_date_time)
        filemenu.add_command(label="Save to Log", command=self.save_to_log)
        filemenu.add_command(label="Change Background", command=self.change_background)
        filemenu.add_separator()
        filemenu.add_command(label="Exit", command=master.quit)
        menubar.add_cascade(label="File", menu=filemenu)
        master.config(menu=menubar)

    def get_date_time(self):
        now = datetime.datetime.now()
        date_time_string = now.strftime("%Y-%m-%d %H:%M:%S")
        self.text_area.delete("1.0", tk.END)
        self.text_area.insert("1.0", date_time_string)

    def save_to_log(self):
        content = self.text_area.get("1.0", tk.END)
        try:
            with open("log.txt", "a") as f:
                f.write(content + "\n")
            messagebox.showinfo("Success", "Content saved to log.txt")
        except Exception as e:
            messagebox.showerror("Error", f"Failed to save to log: {e}")

    def change_background(self):
        if self.random_green_hue is None:
           self.random_green_hue = self.generate_random_green_hue()
        self.master.configure(background=self.random_green_hue)


    def generate_random_green_hue(self):
         # Generates a random hex color code for a green hue.
         hue = random.randint(30, 150) # Green hues are roughly between 60 and 180 on the color wheel.  Adjusting to 30-150 to allow for some variations.
         return "#{:02x}{:02x}{:02x}".format(0, hue, 0)


root = tk.Tk()
app = App(root)
root.mainloop()
